-- sys
DROP TABLE IF EXISTS `sys_user`;
DROP TABLE IF EXISTS `sys_role`;
DROP TABLE IF EXISTS `sys_user_role`;
DROP TABLE IF EXISTS `sys_resource`;
DROP TABLE IF EXISTS `sys_role_resource`;
DROP TABLE IF EXISTS `sys_file`;
DROP TABLE IF EXISTS `sys_dict`;
DROP TABLE IF EXISTS `sys_config`;
-- dc_store
DROP TABLE IF EXISTS `dc_env`;
DROP TABLE IF EXISTS `dc_env_file`;
DROP TABLE IF EXISTS `dc_store`;
DROP TABLE IF EXISTS `dc_store_param`;
DROP TABLE IF EXISTS `dc_graph_store`;
-- dc_metadata
DROP TABLE IF EXISTS `dc_graph`;
DROP TABLE IF EXISTS `dc_schema`;
DROP TABLE IF EXISTS `dc_schema_field`;
DROP TABLE IF EXISTS `dc_vertex_edge`;
-- dc_task
DROP TABLE IF EXISTS `dc_task`;
DROP TABLE IF EXISTS `dc_task_instance`;
DROP TABLE IF EXISTS `dc_task_meta`;
