INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1001', 'graph_test', 'company', 'transfer', 'test_test');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1002', 'graph500', 'vertex', 'vertex', 'edge');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1003', 'test', 'vertex', 'vertex', 'edge');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1004', 'test', 'Company', 'Person', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1005', 'test', 'Person', 'Company', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1006', 'test', 'Person', 'Company', 'te_invest');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1007', 'test', 'Person', 'Company', 'te_officer');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1008', 'test', 'Person', 'Company', 'te_transfer');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1009', 'gap_test_000', 'Company', 'Company', 'te_invest');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1010', 'gap_test_000', 'Person', 'Company', 'te_invest');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1011', 'gap_test_000', 'Person', 'Company', 'te_officer');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1012', 'gap_test_000', 'Company', 'Company', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1013', 'gap_test_000', 'Person', 'Company', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1014', 'gap_test_000', 'Company', 'Person', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1015', 'sz_haizhi_test', 'te_invest', '', 'te_invest');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1016', 'sz_haizhi_test', 'Company', 'Person', 'te_guarantee');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1017', 'sz_haizhi_test', 'Person', 'Company', 'te_officer');

INSERT INTO `graph_dev`.`dc_vertex_edge` (`id`, `graph`, `from_vertex`, `to_vertex`, `edge`)
VALUES ('1018', 'test', 'Person', 'Company', 'testCollection');

